modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
issueTrackerURL="https://github.com/MapperTV/embellishcraft/issues"
[[mods]]
modId="embellishcraft"
version="${file.jarVersion}"
displayName="EmbellishCraft"
#updateJSONURL="http://myurl.me/"
displayURL="http://mapper.tv/embellishcraft/"
logoFile="embellishcraft_logo.png"
credits="The Forge team and community for the help and resources. Quark for the cobblestone brick texture."
authors="Mapper"
description='''EmbellishCraft is a mod that adds various decorative elements to Minecraft.'''

[[dependencies.embellishcraft]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.embellishcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.embellishcraft]]
    modId="mapperbase"
    mandatory=true
    versionRange="[1.18.1-4.0,)"
    ordering="AFTER"
    side="BOTH"