modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/KillerMapper/embellishcraft/issues"
logoFile="embellishcraft_logo.png"
[[mods]]
modId="embellishcraft"
version="${file.jarVersion}"
displayName="EmbellishCraft"
#updateJSONURL="http://myurl.me/"
displayURL="http://mapper.tv/embellishcraft/"
credits="The Forge team and community for the help and resources."
authors="Mapper"
description='''EmbellishCraft is a mod that adds various decorative elements to Minecraft.'''

[[dependencies.embellishcraft]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.embellishcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.embellishcraft]]
    modId="mapperbase"
    mandatory=true
    versionRange="[1.15.2-1.0,]"
    ordering="NONE"
    side="BOTH"